### ISSUE TITLE
Mock control plane didn't show any NGINX information

### ISSUE THREAD

**Issue by weiliang1216** [nginx/agent#164]
**nginx & nginx-agent works as following**
<img width="733" alt="image" src="https://user-images.githubusercontent.com/8175899/211575669-0455a984-99c8-44cd-bbe4-3d545b1ece26.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/8175899/211575982-41f8354c-5851-4cb2-a194-f9fc302d017b.png">

**Mock Control Plane show the GUI**
<img width="624" alt="image" src="https://user-images.githubusercontent.com/8175899/211575278-80c96e83-f45e-442a-8481-a7aa75b9b344.png">

**But nothing in it...**
<img width="409" alt="image" src="https://user-images.githubusercontent.com/8175899/211575433-be2b1004-4430-4e49-a2b9-6a8600cda534.png">

How to resolve the issue?

**Comment by dhurley** [comment]
Hi @weiliang1216, have you updated your `nginx-agent.conf` to enable gRPC https://github.com/nginx/agent#enabling-the-grpc-interface?

Would you be able to provide what your `nginx-agent.conf` file looks like?
Also would you be able to provide the logs for the nginx-agent? (log file should be located located here `/var/log/nginx-agent/agent.log`)

**Comment by weiliang1216** [comment]
The issue resolved. Looks like it will take quite a long time.
It took about 15 mins to show the contents.
