### ISSUE TITLE
Add option to ignore sensitive info while parsing nginx configs

### ISSUE THREAD

**Issue by nkashiv** [nginx/agent#229]
Currently the agent uploads all the Nginx config files that are in the `config_dirs` path. 

However a user may not be comfortable with sending their Nginx configs incase it contains sensitive information they want to protect. 

The proposed enhancement is to add an option to sanitize the contents of the Configs using Crossplane's Ignore Directives like:
- 'ssl_certificate_key'
- 'ssl_client_certificate'
- 'ssl_password_file'
-  'ssl_stapling_file'
-  'ssl_trusted_certificate'
-  'auth_basic_user_file'
-  'secure_link_secret'
Before uploading them to the controller.

**Comment by mtbChef** [comment]
Thanks @nkashiv! We've added this enhancement to the backlog and will evaluate it for roadmap fit
