### ISSUE TITLE
Nginx agent restarts after new installation

### ISSUE THREAD

**Issue by ddominguez2093** [nginx/agent#231]
When check the status of the agent it shows
systemctl status nginx-agent • nginx-agent.service - NGINX Agent Loaded: loaded (/etc/systemd/system/ nginx-agent.service; enabled; vendor preset: disabled) Active: activating (auto-restart) (Result: exit-code) since Tue 2023-02-28 21:26:48 CST; 2s ago Docs: https://github.com/nginx/ agent#readme Process: 10364 ExecStart./usr/bininginx-agent (code=exited, status=2) Process: 10361 ExecStartPre=/bin/mkdir -p /var/log/nginx-agent (code=exited, status=0/SUCCESS) Process: 10359 ExecStartPre=/bin/mkdir -p /var/run/nginx-agent (code=exited, status=0/SUCCESS) Main PID: 10364 (code=exited, status=2) 

in the agent.log file only shows when agent send data to Instance Manager
time="2023-02-28T21:34:06-06:00" level=info msg="setting displayName to -----"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 0 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 1 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 2 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 3 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 4 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 5 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 6 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 7 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 8 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 9 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 10 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 11 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 12 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload: Sending data chunk data 13 (messageId=83e8ff10-a4f0-4ba2-90da-a0add60139e5)"
time="2023-02-28T21:34:06-06:00" level=info msg="Upload sending done 83e8ff10-a4f0-4ba2-90da-a0add60139e5 (chunks=14)"

**Comment by ja20222** [comment]
Hi @ddominguez2093 , we will close this and if the issue is still re-occurring we can reopen it if you reach out to us.  

@mtbChef
