### ISSUE TITLE
Increase coverage in NGINX config unit tests 

### ISSUE THREAD

**Issue by ja20222** [nginx/agent#276]
There are a few areas of improvement for the unit tests for parsing nginx configs with ssl directives and cert files that could be improved:

1. Should test other ssl directives than just `ssl_certificate` since there are several that are supposed to add aux files.

1. Should provide a way to ensure the various cert metadata are being determined properly
    1. Currently, the tests use the same exact code as the production code to parse the `Validity.NotBefore`, `Validity.NotAfter`, `SerialNumber`, `Fingerprint`, `SubjectKeyIdentifier`, `AuthorityKeyIdentifier`, which means the values are not being compared against expected knowns - they are being compared to themselves
    1. See here where these properties are simply being applied to the expected data before asserting equality:  

       [config_helpers_test.go](https://github.com/nginx/agent/blob/main/sdk/config_helpers_test.go)

1. Consider testing other supported algorithms than just RSA - like DSA, ECDSA, EdDSA and/or ECIES

**Comment by ja20222** [comment]
Hi @rorybakerfmr, we're glad to see that you're interested in contributing to our project!  This "good first issue" is a great place to start.  You can find more information about the bug in the issue description above.
Can you please assign this to you or the participant who wishes to work on it?

For [259](https://github.com/nginx/agent/issues/259), can you also comment on it to say that you or your team are interested in contributing on this and assign to the participant who wishes to work on it?

If you have any questions or need help, please don't hesitate to ask. We're here to support you.

We look forward to your contribution and welcome you to our community!

James

**Comment by vjoutlook** [comment]
I would like to look into this

**Comment by ja20222** [comment]
Hi Viresh, we're glad to see that you're interested in contributing to our project NGINX Agent ! 

This "good first issue" is a great place to start.  Can you assign it to yourself to get started? 

If you have any questions or need help, please don't hesitate to ask. We're here to support you.

We look forward to your contribution and welcome you to our community!

James

@vjoutlook

**Comment by ja20222** [comment]
Hi Viresh, did you manage to work on this item?

Or do you need any help on it ?

Many thanks
James 
@vjoutlook

**Comment by vjoutlook** [comment]
@ja20222 please unassign this.  I am not able to invest as much time as I was planning.  Learning Golang itself is taking time for me.

**Comment by arsenalzp** [comment]
Hello,
Can I pick this issue up?
I examined docs, code and it looks clear for me. 
Could you please tell me the expected time constraints if any.

**Comment by ja20222** [comment]
Thank you Oleksandr for picking up this issue from our project NGINX Agent.

Dean has assigned it to you now. 

If you have any questions or need help, please don't hesitate to ask. We're here to support you.

Many thanks

James

**Comment by arsenalzp** [comment]
Hello,
PR was created and it is waiting for reviewing and approval.

**Comment by arsenalzp** [comment]
Hello,
PR to this issue was created.
Could you please review it and approve?
Thank you!
