### ISSUE TITLE
Update GetNetOverflow function to use nstat instead of netstat

### ISSUE THREAD

**Issue by ja20222** [nginx/agent#277]
`nstat` is installed on linux by default so we can use that instead of relying on netstat.

To get the network overflow run the following command:

`$ nstat -az | grep -i TcpExtListenOverflows`

which will return the following output:
```
TcpExtListenOverflows           0                  0.0
```

The NGINX Agent should parse the particular output and populate the float64 : https://github.com/nginx/agent/blob/709e4027601cd05a82c7bf7060227618903035b9/src/core/network/network.go#L59

Ensure consistent output - Rocky Linux 9 (x86_64) and AlmaLinux 8 (x86_64), Ubuntu 22, RHEL 8, SUSE 15, FreeBSD 13 (pasted in the PR output)

**Comment by Harshitsoni2000** [comment]
Hi @Dean-Coakley , @ja20222 . I would love to work on this issue. Could you throw some light on how I can begin?

**Comment by Dean-Coakley** [comment]
Hi @Harshitsoni2000 

First I recommend following this section of our README to setup a development environment: https://github.com/nginx/agent#development-environment-setup

If that goes ok, some steps to get started:
1. Replace the usage of `netstat` command with `nstat -az` in https://github.com/nginx/agent/blob/709e4027601cd05a82c7bf7060227618903035b9/src/core/network/network.go#L59
2. Replace the regex to parse the new value correctly: https://github.com/nginx/agent/blob/709e4027601cd05a82c7bf7060227618903035b9/src/core/network/network.go#L41
3. Enable parsing of NetOverflow on `linux`
