### ISSUE TITLE
Nginx agent returns invalid metrics after the first correct result.

### ISSUE THREAD

**Issue by Soliiiii** [nginx/agent#284]
nginx agent works perfectly when I first install it and try getting metric at http://localhost:8081/metrics/, but just seconds later I'd get the error response below when trying getting metrics again:

"
An error has occurred while serving metrics:
106 error(s) occurred:
* collected metric "nginx_upstream_response_failed" { ...} **was collected before with the same name and label values**
...
"

I tried to search for help but there are barely no answers.  Is this a bug or just something caused by my system setting? I install the nginx agent following the installation tutorial strictly.

**Comment by dhurley** [comment]
Hi @Soliiiii, I wasn't able to reproduce the issue that you saw.
Would you be able to provide additional information around your setup?
Like for example, could you provide the following:

- Agent logs located here: `/var/log/nginx-agent/agent.log`
- Agent configuration located here: `/etc/nginx-agent/nginx-agent.conf`
- Information about the NGINX instance that you are using (i.e. version of instance, config file, etc)
- Information about the operating system that you are running the NGINX Agent on.
