### ISSUE TITLE
path to agent-dynamic.conf should be configurable

### ISSUE THREAD

**Issue by dekobon** [nginx/agent#337]
If the file `agent-dynamic.conf` file does not exist in one of the default paths, such as `/var/lib/nginx-agent/`, the Agent will fail to start up, with the following error:
```
$ ./build/nginx-agent --config-dirs /opt/nginx-agent/
WARN[0000] Unable to read dynamic config (/var/lib/nginx-agent/agent-dynamic.conf), got the following error: stat /var/lib/nginx-agent/agent-dynamic.conf: no such file or directory 
INFO[0000] Writing the following file to disk: /var/lib/nginx-agent/agent-dynamic.conf 
FATA[0000] Unable to load properties from config files (/home/elijah/Development/Open_Source/nginx-agent/nginx-agent.conf, /var/lib/nginx-agent/agent-dynamic.conf) - error attempting to create directory for dynamic config (/var/lib/nginx-agent/), got the following error: mkdir /var/lib/nginx-agent/: permission denied 
```

Perhaps this is by design, but it is unclear if the path of `agent-dynamic.conf` is allowed to be configurable.

**Comment by dekobon** [comment]
Upon further inspection, it appears that agent-dynamic.conf is hard-coded to the location `/var/lib/nginx-agent/agent-dynamic.conf`. Ideally, the location of this file should be able to be specified so that developers of agent do not need to issue sudo commands to run install the agent.

**Comment by ja20222** [comment]
Hi Dekobon, we have started working on this. Please expect this in 2.30 version of the NGINX AGENT. 

@dekobon
