### ISSUE TITLE
"include" directive is not allowed within an "if" block

### ISSUE THREAD

**Issue by dareste** [nginx/agent#505]
The following valid nginx config is mistakenly marked as illegal by the Agent:

```
server {
    listen       80 default_server;
    server_name  localhost;

    location / {

        if ($request_method = 'OPTIONS') 
        {
          include conf.d/some_file;
          return 204;
        }

        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}
```

The agent fails to write the configuration with:

```
time="2023-10-17T08:47:26Z" level=info msg="Updating NGINX config"
time="2023-10-17T08:47:26Z" level=info msg="Attempting to run command: /usr/sbin/nginx with args -t -c /etc/nginx/nginx.conf"
time="2023-10-17T08:47:26Z" level=info msg="Config validated:\nnginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: configuration file /etc/nginx/nginx.conf test is successful\n"
time="2023-10-17T08:47:26Z" level=error msg="Config apply failed (write): error running nginx -t -c /etc/nginx/nginx.conf:\n error reading config from /etc/nginx/nginx.conf, error: \"include\" directive is not allowed here in /etc/nginx/conf.d/default.conf:11"
```

This is caused by a bug in `nginx-go-crossplane` (see https://github.com/nginxinc/nginx-go-crossplane/issues/72). Once we have a new `nginx-go-crossplane` version, Agent will have to point to that one to solve this validation issue.

**Comment by oliveromahony** [comment]
I've updated the version of crossplane in https://github.com/nginx/agent/pull/504

Let me know if that resolves the issue

**Comment by dareste** [comment]
@oliveromahony, apologies that I wasn't clear. The latest crossplane version (0.4.32) is still affected by the issue. I have submitted a [PR](https://github.com/nginxinc/nginx-go-crossplane/pull/74) with the fix. Once it's merged and a new crossplane version is bumped, we'll have to change it here.

**Comment by dareste** [comment]
@oliveromahony crossplane 0.4.33 is published and fixes this issue.

**Comment by oliveromahony** [comment]
Merged with https://github.com/nginx/agent/pull/512 - this should be in the next release of the NGINX Agent
