### ISSUE TITLE
How to let the agent collect the information in access.log?

### ISSUE THREAD

**Issue by chengshuyi** [nginx/agent#513]
I found that the default agent will not collect the information in access.log, so how to let the agent collect the information in access.log?

**Comment by oliveromahony** [comment]
Hi @chengshuyi, the NGINX config needs the access log information present. If this isn't present the NGINX Agent won't read it. 

An example config would be:
```
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"'
                      '"$upstream_cache_status"';
  
    access_log  /var/log/nginx/access.log  main;
```

in this case the NGINX Agent would read the log_format mentioned above to collect OSS metrics from NGINX. 
If the `access_log` and `log_format` directives are present in your configuration, can you post what NGINX config you have and I can see if there is something else we can take a look at being the potential cause?

**Comment by chengshuyi** [comment]
Thank you very much for your reply. I can collect access.log by adding advanced-metrics to the nginx-agent.conf file.
```
extensions:
   -advanced-metrics
```

**Comment by oliveromahony** [comment]
Ah, we have 2 sets of metrics being collected. What you mentioned comes from the NGINX Plus Metrics Module (this needs to be installed on NGINX Plus). The documentation for that is here: https://docs.nginx.com/nginx-management-suite/nginx-agent/install-nginx-plus-advanced-metrics/
