### ISSUE TITLE
How to config multiple grpcs proxy in same location with different headers?

### ISSUE THREAD

**Issue by kobofare** [nginx/agent#531]
environment:
 macos: 12.7
 nginx: 1.25.3

/usr/local/etc/nginx/nginx.conf :

       location /yeying.api.user.User/ {
           grpc_set_header Content-Type application/grpc;
           grpc_socket_keepalive on;
           if ($http_app_name = "store") {
               grpc_pass grpcs://localhost:9202;
               grpc_ssl_trusted_certificate /path1/cert/ca-cert.pem;
               grpc_ssl_certificate /path1/cert/client-cert.pem;
               grpc_ssl_certificate_key /path1/cert/client-key.pem;
               grpc_ssl_verify on;
               grpc_ssl_server_name on; 
               break;
           }

           if ($http_app_name = "robot") {
               grpc_pass grpcs://www.robot.pub:9002;
               grpc_set_header Te trailers;
               grpc_ssl_trusted_certificate /path2/cert/ca-cert.pem;
               grpc_ssl_certificate /path2/cert/client-cert.pem;
               grpc_ssl_certificate_key /path2/cert/client-key.pem;
               grpc_ssl_verify on;
               grpc_ssl_server_name on;
               break;
           }

           if ($http_app_name = "node") {
               grpc_pass grpcs://localhost:9103;
               grpc_ssl_trusted_certificate /path3/cert/ca-cert.pem;
               grpc_ssl_certificate /path3/cert/client-cert.pem;
               grpc_ssl_certificate_key /path3/cert/client-key.pem;
               grpc_ssl_verify on;
               grpc_ssl_server_name on;
               break;
           }
        }

meet error：
023/12/19 09:15:23 [emerg] 44181#0: "grpc_ssl_trusted_certificate" directive is not allowed here in /usr/local/etc/nginx/nginx.conf:65

**Comment by ja20222** [comment]
Hi @kobofare , 

Thank you for your question.

This looks to be a NGINX related question and not a NGINX Agent related item. 

If you have any questions you can ask here in the NGINX Slack community group  https://nginxcommunity.slack.com/archives/C02T18NMZU4.

Please let me know if this works for you?

Best regards, 

James

**Comment by ja20222** [comment]
Hi @kobofare, 

Closing this for now. 

Please feel free to open a new issue if you need to. 

Best regards, 

James
