### ISSUE TITLE
How do I retrieve the NGINX config?

### ISSUE THREAD

**Issue by 7wingfly** [nginx/agent#567]
I see there is an API end-point for applying NGINX configuration (`PUT /nginx/config/`), but how do I go about getting the current configuration? NIM is able to do this so I assume its posssible somehow?

**Comment by oliveromahony** [comment]
Thanks for the issue @7wingfly. You can see how to get a NGINX config from the Management Server perspective in https://github.com/nginx/agent/blob/main/sdk/examples/server.go#L83 

Right now there is no REST API on the Agent that allows you to retrieve the configuration. Can you provide more context on why this is required?

**Comment by oCHRISo** [comment]
Hi @7wingfly 

As there hasn't been any further response, I'm going to close this issue. If you have any other questions or need further assistance, please feel free to reopen this issue or create a new one.

Thank you!

Best regards,
@oCHRISo
